#ifndef QPHIDGETMOCK_GLOBAL_H
#define QPHIDGETMOCK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QPHIDGETMOCK_LIBRARY)
#  define QPHIDGETMOCKSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QPHIDGETMOCKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QPHIDGETMOCK_GLOBAL_H
