#ifndef QPHIDGETLIB_GLOBAL_H
#define QPHIDGETLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QPHIDGETLIB_LIBRARY)
#  define QPHIDGETLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QPHIDGETLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QPHIDGETLIB_GLOBAL_H
